index:
  path: /
  controller: App\Controller\IndexController::index
login:
  path: /login
  controller:  App\Controller\LoginController::login
comment:
  path: /comments
  controller: App\Controlller\CommentController::showComment
addComment:
  path: /newComment
  controller: App\Controller\CommentController::addComment
newUser:
  path: /new/User
  controller: App\Controller\UserController::addUser
