index:
   path: /
   controller: App\Controller\IndexController::index
login:
   path: /login
   controller:  App\Controller\LoginController::login
logout:
   path: /logout
   controller: App\Controller\LoginController::logout
comment:
   path: /comments
   controller: App\Controller\CommentController::showComments
newComment:
   path: /new/comment
   controller: App\Controller\CommentController::addComment
newUser:
  path: /new/user
  controller: App\Controller\LoginController::addUser
profile:
  path: /profile
  controller: App\Controller\LoginController::showUserProfile
posts:
  path: /posts
  controller: App\Controller\PostController::showPosts
AddPosts:
  path: /addpost
  controller: App\Controller\PostController::addPost