index:
  path: /
  controller: App\Controller\IndexController::index
login:
  path: /login
  controller:  App\Controller\LoginController::login
comment:
  path: /comments
  controller: App\Controller\CommentController::addComment
newUser:
  path: /new/User
  controller: App\Controller\LoginController::addUser
users:
  path: /users
  controller: App\Controller\LoginController::showUserDetails
